### ISSUE TITLE
Request patient sample metadata

### ISSUE THREAD

**Issue by chenxix1** [mahmoudibrahim/KidneyMap#2]
Hi,

I have trouble with mapping samples to patients.

In the supp.table1, patients are labeled as '1 (CD10+/-)', '2 (CD10+/-)', etc. In the scRNA-seq count matrix, samples are labeled as 'CDp1','CDp2','CDm1',etc. Could you provide a sample-patient mapping table, or do we miss something in your original publication? Your help is much appreciated!

Many thanks in advanced.
Chenxi

**Comment by mahmoudibrahim** [comment]
Hi
Please contact the corresponding author (Rafael Kramann) for more info regarding the patient meta-data. 
Thanks & best wishes
Mahmoud
